name: Issues

on:
  issues:
    types: [opened]

jobs:
  process_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Pull Request Body
        env:
          BODY: ${{ github.event.issue.title }}"
        run: |
          echo "Pull Request Body: $BODY"
