name: Issues

on:
  issues:
    types: [opened]

jobs:
  print_issue_title:
    runs-on: ubuntu-latest
    env:
      ENV_FILE: environment.yml
      ISSUE_TITLE: ${{ github.event.issue.title }}  # 修改为全大写是更好的实践
    name: Print issue title
    steps:
    - run: echo "$ISSUE_TITLE"  # 直接使用环境变量，不需要 ${{ }}
